import type { Product } from "./types";

// Catálogo mock de arranque para SUMMER AI. Mismo espíritu que
// `desktop-tutorial/src/lib/mock-data.ts`: datos desacoplados de la UI,
// listos para reemplazarse por un repositorio real (propio o compartido
// con el Seller Hub) sin tocar ninguna pantalla.

export const products: Product[] = [
  {
    id: "vcp-friends",
    nombre: "VCP Friends",
    categoria: "turismo-joven",
    destino: "Villa Carlos Paz",
    pais: "Argentina",
    fechaSalida: "2026-01-10",
    fechaRegreso: "2026-01-17",
    dias: 8,
    noches: 7,
    hotelNombre: "Hotel Punta Piedras",
    tipoHabitacion: "Cuádruple",
    incluyeAereos: false,
    excursionesIncluidas: ["Boliche Zeppelin", "Rafting en el río", "Noche de casino"],
    precioVenta: 420000,
    moneda: "ARS",
    cupos: 40,
    fechaLimiteReserva: "2025-12-15",
    descripcion: "El clásico viaje de egresados/turismo joven a Villa Carlos Paz, con salidas nocturnas y excursiones grupales.",
    imagenPortada: "/productos/vcp-friends.jpg",
    publicoObjetivo: ["turismo-joven", "grupos-amigos"],
    estado: "activo",
  },
  {
    id: "brasil-floripa",
    nombre: "Floripa Friends",
    categoria: "brasil",
    destino: "Florianópolis",
    pais: "Brasil",
    fechaSalida: "2026-01-20",
    fechaRegreso: "2026-01-27",
    dias: 8,
    noches: 7,
    hotelNombre: "Ingleses Praia Hotel",
    tipoHabitacion: "Triple",
    incluyeAereos: true,
    aeropuertoSalida: "Aeroparque (AEP)",
    excursionesIncluidas: ["City tour por las playas", "Paseo en lancha"],
    precioVenta: 890000,
    moneda: "ARS",
    cupos: 30,
    fechaLimiteReserva: "2025-12-01",
    descripcion: "Grupos de amigos en Florianópolis: playa, vida nocturna y aéreos incluidos desde Buenos Aires.",
    imagenPortada: "/productos/floripa-friends.jpg",
    publicoObjetivo: ["turismo-joven", "grupos-amigos"],
    estado: "activo",
  },
  {
    id: "caribe-punta-cana",
    nombre: "Punta Cana Premium",
    categoria: "caribe",
    destino: "Punta Cana",
    pais: "República Dominicana",
    fechaSalida: "2026-02-05",
    fechaRegreso: "2026-02-12",
    dias: 8,
    noches: 7,
    hotelNombre: "Riu Palace Punta Cana",
    tipoHabitacion: "Doble All Inclusive",
    incluyeAereos: true,
    aeropuertoSalida: "Ezeiza (EZE)",
    excursionesIncluidas: ["Isla Saona"],
    precioVenta: 1450000,
    moneda: "ARS",
    cupos: 12,
    fechaLimiteReserva: "2025-12-20",
    descripcion: "Resort 5 estrellas all inclusive para parejas o viajeros premium que buscan una experiencia aspiracional.",
    imagenPortada: "/productos/punta-cana-premium.jpg",
    publicoObjetivo: ["parejas", "premium"],
    estado: "activo",
  },
];
